[package]
name = "rv"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
anyhow = "1"
ratatui = "0.26"
crossterm = "*"
elf = "0.7"
comfy-table = "6.1.1"